# Generated by Django 3.2.7 on 2021-10-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speciality", models.CharField(max_length=80)),
                ("year_of_entry", models.IntegerField()),
                ("group_number", models.IntegerField()),
            ],
        ),
    ]
