# Generated by Django 3.2.7 on 2021-10-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='speciality',
            field=models.CharField(choices=[('Anesthesiology', 'Anesthesiology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Ophthalmology', 'Ophthalmology'), ('Pathology', 'Pathology'), ('Pediatrics', 'Pediatrics'), ('Psychiatry', 'Psychiatry'), ('Surgery', 'Surgery'), ('Urology', 'Urology')], max_length=40),
        ),
    ]
