# Generated by Django 3.2.7 on 2021-10-17 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enroll_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='graduate_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('\\d{10,14}')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=120, null=True, unique=True),
        ),
    ]
